(()=>{
const AUTH_KEY='napricelo_auth_session';
const style=document.createElement('style');
style.textContent=`#adminUsersPage .admin-wrap{max-width:920px;margin:auto}.admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.admin-list{margin-top:18px}.admin-user-row{border:1px solid #dce7e1;border-radius:10px;padding:12px;margin:8px 0;background:#fff;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.admin-user-row small{display:block;color:#607068;margin-top:3px}.admin-actions{display:flex;gap:6px;flex-wrap:wrap}.admin-actions button{padding:7px 9px;border:1px solid #bfd2c7;border-radius:7px;background:#f5faf7;color:#176b45;font-weight:700}.admin-actions .danger{color:#9d2c25;border-color:#e6bdb9}.admin-msg{padding:10px 12px;border-radius:8px;background:#f4f8f6;margin:10px 0}.admin-card{display:none}@media(max-width:700px){.admin-grid{grid-template-columns:1fr}.admin-user-row{grid-template-columns:1fr}}`;
document.head.appendChild(style);
function getSession(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
async function rpc(action,data={}){const s=getSession();const r=await fetch(`${SUPABASE_URL}/functions/v1/admin-users`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s?.access_token||''}`,'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível concluir a operação.');return d}
async function fetchOwnRole(){const s=getSession();if(!s?.access_token)return null;const r=await fetch(`${SUPABASE_URL}/rest/v1/app_user_roles?select=perfil,ativo,nome,email&user_id=eq.${encodeURIComponent(s.user?.id||'')}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s.access_token}`}});if(!r.ok)return null;const a=await r.json();return a?.[0]||null}
function ensureAdminPage(){if(document.getElementById('adminUsersPage'))return;const sec=document.createElement('section');sec.id='adminUsersPage';sec.className='page';sec.innerHTML=`<div class="admin-wrap"><h2>Administração de acessos</h2><p>Somente o administrador pode criar, alterar ou remover usuários do Napricelo Campo.</p><div id="adminMsg" class="admin-msg">Carregando...</div><form id="adminUserForm"><div class="admin-grid"><label>Nome<input name="nome" required></label><label>E-mail<input name="email" type="email" required></label><label>Perfil<select name="perfil"><option value="tecnico">Técnico</option><option value="operacional">Operacional</option><option value="comercial">Comercial</option><option value="consulta">Consulta</option><option value="administrador">Administrador</option></select></label><label>Senha inicial<input name="password" type="password" minlength="8" required placeholder="mínimo 8 caracteres"></label></div><button class="primary">Criar acesso</button></form><h3 style="margin-top:22px">Usuários autorizados</h3><div id="adminUserList" class="admin-list"></div></div>`;document.querySelector('main')?.appendChild(sec);sec.querySelector('#adminUserForm').onsubmit=createUser}
function ensureAdminCard(){const grid=document.querySelector('#home .grid');if(!grid||document.getElementById('adminUsersCard'))return;const b=document.createElement('button');b.className='card admin-card';b.id='adminUsersCard';b.innerHTML='<b>ADM</b><span>Administração / Usuários</span>';b.onclick=()=>{showPage('adminUsersPage');loadUsers()};grid.appendChild(b)}
function msg(t){const el=document.getElementById('adminMsg');if(el)el.textContent=t||''}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function createUser(e){e.preventDefault();const f=new FormData(e.currentTarget);const btn=e.currentTarget.querySelector('button');btn.disabled=true;msg('Criando acesso...');try{await rpc('create',{nome:f.get('nome'),email:f.get('email'),perfil:f.get('perfil'),password:f.get('password')});e.currentTarget.reset();msg('Acesso criado com sucesso.');await loadUsers()}catch(err){msg(err.message)}finally{btn.disabled=false}}
async function loadUsers(){ensureAdminPage();msg('Carregando usuários...');try{const d=await rpc('list');const list=document.getElementById('adminUserList');list.innerHTML='';(d.users||[]).forEach(u=>{const row=document.createElement('div');row.className='admin-user-row';row.innerHTML=`<div><strong>${esc(u.nome||u.email)}</strong><small>${esc(u.email)} • ${esc(u.perfil)} • ${u.ativo?'Ativo':'Desativado'}</small></div><div class="admin-actions"><button data-edit>Alterar perfil</button><button data-toggle>${u.ativo?'Desativar':'Ativar'}</button><button class="danger" data-remove>Remover</button></div>`;row.querySelector('[data-edit]').onclick=async()=>{const p=prompt('Novo perfil: administrador, tecnico, operacional, comercial ou consulta',u.perfil);if(!p)return;try{await rpc('update',{user_id:u.user_id,perfil:p});await loadUsers()}catch(e){alert(e.message)}};row.querySelector('[data-toggle]').onclick=async()=>{if(!confirm(`${u.ativo?'Desativar':'Ativar'} o acesso de ${u.nome||u.email}?`))return;try{await rpc('update',{user_id:u.user_id,ativo:!u.ativo});await loadUsers()}catch(e){alert(e.message)}};row.querySelector('[data-remove]').onclick=async()=>{if(!confirm(`Remover definitivamente o acesso de ${u.nome||u.email}?`))return;try{await rpc('remove',{user_id:u.user_id});await loadUsers()}catch(e){alert(e.message)}};list.appendChild(row)});msg('Gerencie abaixo os acessos autorizados.')}catch(err){msg(err.message)}}
async function init(){ensureAdminPage();ensureAdminCard();const role=await fetchOwnRole();const card=document.getElementById('adminUsersCard');if(role?.ativo&&role.perfil==='administrador'){if(card)card.style.display='flex';window.NAPRICELO_IS_ADMIN=true}else{if(card)card.style.display='none';window.NAPRICELO_IS_ADMIN=false}}
window.addEventListener('load',()=>setTimeout(init,400));
window.addEventListener('napricelo-auth-changed',()=>setTimeout(init,200));
setTimeout(init,300);
})();