const $=s=>document.querySelector(s);
const db={get:k=>JSON.parse(localStorage.getItem(k)||"[]"),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const SUPABASE_URL="https://zhdcekhqntytiswdjqaw.supabase.co";
const SUPABASE_KEY="sb_publishable_bcVp32RbgpOHOYbmjcaAPg_G4fiLDIw";
const SUPABASE_HEADERS={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,"Content-Type":"application/json"};
const RESPONSAVEIS_TECNICOS={
 "Marcelo de Araujo Santos":{nome:"Marcelo de Araujo Santos",titulo:"Técnico em Meio Ambiente",cft:"07978312666"},
 "Marco Antônio de Araujo Santos":{nome:"Marco Antônio de Araujo Santos",titulo:"Responsável Técnico",cft:"07636895641"}
};
let equipCache=[];
async function carregarEquipamentosNuvem(){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/equipamentos?select=*&order=id.asc`,{headers:SUPABASE_HEADERS});if(!r.ok)throw new Error(`Supabase ${r.status}`);equipCache=await r.json();db.set("equip",equipCache);}catch(err){console.warn("Usando equipamentos locais.",err);equipCache=db.get("equip");}refreshEquipSelectors();}
async function salvarEquipamentoNuvem(o){const payload={codigo:o.codigo||null,cliente:o.cliente||null,unidade:o.unidade||null,municipio:o.municipio||null,tipo:o.tipo||null,modelo:o.modelo||null,capacidade:o.capacidade||null,localizacao:o.localizacao||o.local||null,observacoes:o.observacoes||null};const r=await fetch(`${SUPABASE_URL}/rest/v1/equipamentos`,{method:"POST",headers:{...SUPABASE_HEADERS,Prefer:"return=representation"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());return (await r.json())[0];}
async function salvarAnaliseNuvem(o,eq){const num=v=>v===""||v==null?null:Number(v);const payload={equipamento_id:eq.id||null,codigo:eq.codigo||null,cliente:eq.cliente||null,unidade:eq.unidade||null,municipio:eq.municipio||null,tipo:eq.tipo||null,data:o.data||null,horario:o.hora||null,responsavel:o.responsavel||null,ponto:o.ponto||null,ph:num(o.ph),temperatura:num(o.temperatura),aspecto:o.aspecto||null,odor:o.odor||null,dbo:num(o.dbo),dqo:num(o.dqo),solidos:num(o.solidos),oleos:num(o.oleos),outros_param:o.outros_param||null,observacoes:o.observacoes||null};const r=await fetch(`${SUPABASE_URL}/rest/v1/analises`,{method:"POST",headers:{...SUPABASE_HEADERS,Prefer:"return=representation"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());return (await r.json())[0];}
async function salvarManutencaoNuvem(o,eq){const campos={};Object.keys(o).filter(k=>/^campo\d+$/.test(k)).forEach(k=>campos[k]=o[k]||"");const payload={equipamento_id:eq.id||null,tipo:o.tipo||null,codigo:eq.codigo||null,cliente:eq.cliente||null,unidade:eq.unidade||null,municipio:eq.municipio||null,localizacao:eq.localizacao||eq.local||null,data:o.data||null,tecnico:o.tecnico||null,checks:o.checks||[],campos,observacoes:o.observacoes||null};const r=await fetch(`${SUPABASE_URL}/rest/v1/manutencoes`,{method:"POST",headers:{...SUPABASE_HEADERS,Prefer:"return=representation"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());return (await r.json())[0];}
function eqs(){return equipCache.length?equipCache:db.get("equip")}
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");if(id==="historico")renderHistorico("equip");if(["biodigestor","gordura","sao","analise"].includes(id))refreshEquipSelectors();scrollTo(0,0);}
function equipId(e){return e.codigo||`${e.tipo}-${Math.random()}`}
function equipLabel(e){return `${e.codigo} — ${e.cliente||""}${e.unidade?" / "+e.unidade:""}`}
function refreshEquipSelectors(){const eq=eqs();document.querySelectorAll(".equipSelect").forEach(sel=>{const atual=sel.value;sel.innerHTML='<option value="">Selecione...</option>'+eq.map((e,i)=>`<option value="${i}">${equipLabel(e)}</option>`).join("");if(atual)sel.value=atual;});const a=$("#analiseEquip");if(a){const atual=a.value;a.innerHTML='<option value="">Selecione...</option>'+eq.map((e,i)=>`<option value="${i}">${equipLabel(e)}</option>`).join("");if(atual)a.value=atual;updateAutoAnalise();}}
const configs={biodigestor:{titulo:"POP – Manutenção de Biodigestor",checks:["Identificação/código conferido","Tampas e acessos em condição adequada","Tubulações de entrada e saída verificadas","Registro/dispositivo de descarga verificado","Ausência de vazamentos","Condição do lodo/efluente avaliada","Leito de secagem verificado","Condição do entorno verificada"],campos:["Descarga de lodo realizada?","Ocupação do leito / nível","Material seco retirado?","Anomalias / ações necessárias"]},gordura:{titulo:"POP – Caixa de Gordura",checks:["Identificação/código conferido","Tampa e acesso verificados","Acúmulo de gordura avaliado","Sólidos e resíduos retirados","Entrada e saída desobstruídas","Limpeza concluída","Condição final sem vazamentos"],campos:["Volume/condição do material retirado","Acondicionamento / permanência","Anomalias / recomendações"]},sao:{titulo:"POP – Caixa Separadora de Água e Óleo – SAO",checks:["Identificação/código conferido","Inspeção antes da abertura","Tampas e acessos verificados","Lama/barro e sólidos avaliados","Material oleoso avaliado","Compartimentos acessíveis limpos","Material acondicionado em recipiente compatível e fechado","Condição hidráulica final verificada"],campos:["Quantidade/condição do material retirado","Acondicionamento temporário","Não conformidades / recomendações"]}};
function popHTML(tipo){const c=configs[tipo];return `<h2>${c.titulo}</h2><p>Selecione um equipamento já cadastrado para evitar redigitação.</p><form class="manutForm" data-tipo="${tipo}"><label>Equipamento cadastrado<select class="equipSelect" name="equip_index" required></select></label><div class="autobox equipAuto">Selecione o equipamento.</div><label>Data<input name="data" type="date" required></label><label>Responsável técnico<select name="tecnico" required><option value="">Selecione...</option><option>Marcelo de Araujo Santos</option><option>Marco Antônio de Araujo Santos</option></select></label><h3>Checklist</h3>${c.checks.map((x,i)=>`<label class="check"><input type="checkbox" name="ck${i}"> <span>${x}</span></label>`).join("")}${c.campos.map((x,i)=>`<label>${x}<textarea name="campo${i}"></textarea></label>`).join("")}<h3>Registro fotográfico</h3><div class="photo">Antes<input type="file" accept="image/*" capture="environment"></div><div class="photo">Durante<input type="file" accept="image/*" capture="environment"></div><div class="photo">Depois<input type="file" accept="image/*" capture="environment"></div><label>Observações finais<textarea name="observacoes"></textarea></label><button class="primary">Salvar manutenção</button></form>`;}
["biodigestor","gordura","sao"].forEach(t=>$("#"+t+" .pop").innerHTML=popHTML(t));
$("#equipForm").addEventListener("submit",async e=>{e.preventDefault();const o={...Object.fromEntries(new FormData(e.target)),criado:new Date().toLocaleString("pt-BR")};if(eqs().some(x=>x.codigo?.trim().toLowerCase()===o.codigo.trim().toLowerCase()))return alert("Já existe equipamento com esse código.");try{const salvo=await salvarEquipamentoNuvem(o);equipCache.push({...o,...salvo});db.set("equip",equipCache);alert("Equipamento salvo na nuvem.");e.target.reset();refreshEquipSelectors();showPage("home");}catch(err){console.error(err);alert("Não foi possível salvar no banco online. Verifique a internet e tente novamente.");}});
document.querySelectorAll(".manutForm").forEach(f=>{const sel=f.querySelector(".equipSelect"),box=f.querySelector(".equipAuto");sel.addEventListener("change",()=>{const e=eqs()[Number(sel.value)];box.innerHTML=e?`<b>${e.codigo}</b><br>${e.cliente||""}${e.unidade?" • "+e.unidade:""}<br>${e.municipio||""}${(e.localizacao||e.local)?" • "+(e.localizacao||e.local):""}`:"Selecione o equipamento.";});f.addEventListener("submit",async ev=>{ev.preventDefault();const idx=Number(sel.value),eq=eqs()[idx];if(!eq)return alert("Selecione um equipamento.");const fd=new FormData(f),o={tipo:f.dataset.tipo,equip_index:idx,codigo:eq.codigo,cliente:eq.cliente,unidade:eq.unidade,municipio:eq.municipio,local:eq.localizacao||eq.local,criado:new Date().toLocaleString("pt-BR")};for(let[k,v]of fd.entries())if(!(v instanceof File))o[k]=v;o.checks=[...f.querySelectorAll('input[type=checkbox]')].map(x=>x.checked);try{const salvo=await salvarManutencaoNuvem(o,eq);const a=db.get("manut");a.push({...o,...salvo});db.set("manut",a);alert("Manutenção salva na nuvem.");f.reset();box.textContent="Selecione o equipamento.";showPage("home");}catch(err){console.error(err);alert("Não foi possível salvar a manutenção na nuvem. Verifique a internet e tente novamente.");}});});
$("#analiseEquip").addEventListener("change",updateAutoAnalise);function updateAutoAnalise(){const idx=$("#analiseEquip").value,box=$("#analiseAuto"),e=eqs()[Number(idx)];box.innerHTML=e?`<b>${e.codigo}</b><br>${e.cliente||""}${e.unidade?" • "+e.unidade:""}<br>${e.municipio||""}${(e.localizacao||e.local)?" • "+(e.localizacao||e.local):""}<br>${e.tipo||""}${e.capacidade?" • "+e.capacidade:""}`:"Selecione o equipamento.";}
$("#analiseForm").addEventListener("submit",async e=>{e.preventDefault();const idx=Number($("#analiseEquip").value),eq=eqs()[idx];if(!eq)return alert("Selecione um equipamento.");const fd=new FormData(e.target),o={equip_index:idx,codigo:eq.codigo,cliente:eq.cliente,unidade:eq.unidade,municipio:eq.municipio,local:eq.localizacao||eq.local,tipo:eq.tipo,criado:new Date().toLocaleString("pt-BR")};for(let[k,v]of fd.entries())if(!(v instanceof File))o[k]=v;try{const salvo=await salvarAnaliseNuvem(o,eq);const a=db.get("analises");a.push({...o,...salvo});db.set("analises",a);alert("Análise salva na nuvem.");e.target.reset();updateAutoAnalise();showPage("home");}catch(err){console.error(err);alert("Não foi possível salvar a análise na nuvem. Verifique a internet e tente novamente.");}});
$("#tipo").addEventListener("change",e=>{let p={Biodigestor:"BD","Caixa de Gordura":"CG",SAO:"SAO","Ecobio Reator":"ER"}[e.target.value];$("#codigo").placeholder=`Ex.: ${p}-01`});
function excluir(tipo,i){if(!confirm("Excluir este registro?"))return;const a=db.get(tipo);a.splice(i,1);db.set(tipo,a);renderHistorico(tipo);}
function exportar(){const data={equipamentos:eqs(),manutencoes:db.get("manut"),analises:db.get("analises"),exportado:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="napricelo-registros-v2.json";a.click();URL.revokeObjectURL(a.href);}
carregarEquipamentosNuvem();
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");