(()=>{
const AUTH_KEY='napricelo_auth_session';
const css=`
#authGate{position:fixed;inset:0;z-index:99999;background:#eef3f0;display:flex;align-items:center;justify-content:center;padding:20px;font-family:Arial,sans-serif}
#authGate.hidden{display:none}.auth-card{width:min(420px,100%);background:#fff;border-radius:18px;padding:28px;box-shadow:0 14px 40px #0002}.auth-brand{display:flex;gap:12px;align-items:center;margin-bottom:22px}.auth-logo{width:46px;height:46px;border-radius:50%;background:#176b45;color:#fff;display:grid;place-items:center;font-weight:800;font-size:22px}.auth-brand strong{display:block;color:#176b45;font-size:20px}.auth-brand small{color:#607068}.auth-card h2{margin:0 0 6px;color:#173d2d}.auth-card p{margin:0 0 18px;color:#607068;font-size:14px;line-height:1.4}.auth-card label{display:block;font-weight:700;font-size:13px;margin:12px 0 5px}.auth-card input{box-sizing:border-box;width:100%;padding:12px;border:1px solid #cbd8d1;border-radius:9px;font-size:16px}.auth-btn{width:100%;border:0;border-radius:9px;padding:13px;margin-top:16px;background:#176b45;color:#fff;font-weight:700;cursor:pointer}.auth-link{width:100%;border:0;background:transparent;color:#176b45;margin-top:12px;cursor:pointer;text-decoration:underline}.auth-msg{min-height:20px;margin-top:12px!important;font-size:13px!important}.auth-user{position:fixed;right:18px;top:64px;z-index:9990;background:#fff;border:1px solid #dce7e1;border-radius:9px;padding:7px 10px;font-size:12px;box-shadow:0 3px 12px #0001}.auth-user button{border:0;background:transparent;color:#176b45;font-weight:700;cursor:pointer;margin-left:8px}@media(max-width:700px){.auth-user{top:58px;right:8px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const gate=document.createElement('div');gate.id='authGate';gate.innerHTML=`<div class="auth-card"><div class="auth-brand"><div class="auth-logo">N</div><div><strong>NAPRICELO</strong><small>Soluções Ambientais • Campo</small></div></div><h2 id="authTitle">Acesso ao sistema</h2><p id="authHelp">Entre com seu e-mail e senha para acessar os dados de campo.</p><form id="authForm"><label>E-mail</label><input id="authEmail" type="email" autocomplete="username" required><label>Senha</label><input id="authPassword" type="password" autocomplete="current-password" minlength="6" required><button class="auth-btn" id="authSubmit">Entrar</button></form><button class="auth-link" id="authMode" type="button">Criar primeiro acesso</button><p class="auth-msg" id="authMsg"></p></div>`;document.body.appendChild(gate);
let mode='login';
const msg=t=>document.getElementById('authMsg').textContent=t||'';
function loadSecureStorage(){if(document.querySelector('script[data-secure-storage]'))return;const s=document.createElement('script');s.src='secure-storage.js?v=2';s.dataset.secureStorage='1';document.head.appendChild(s)}
function saveSession(s){localStorage.setItem(AUTH_KEY,JSON.stringify(s));applySession(s)}
function getSession(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function applySession(s){if(!s?.access_token)return false;if(window.SUPABASE_HEADERS)window.SUPABASE_HEADERS.Authorization=`Bearer ${s.access_token}`;else if(typeof SUPABASE_HEADERS!=='undefined')SUPABASE_HEADERS.Authorization=`Bearer ${s.access_token}`;gate.classList.add('hidden');showUser(s.user?.email||'Usuário');loadSecureStorage();return true}
function showUser(email){let box=document.getElementById('authUser');if(!box){box=document.createElement('div');box.id='authUser';box.className='auth-user';document.body.appendChild(box)}box.innerHTML=`${email}<button id="authLogout">Sair</button>`;document.getElementById('authLogout').onclick=logout}
async function authRequest(path,body){const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||d.error_description||'Não foi possível concluir o acesso.');return d}
async function logout(){const s=getSession();try{if(s?.access_token)await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s.access_token}`}})}catch{}localStorage.removeItem(AUTH_KEY);document.getElementById('authUser')?.remove();gate.classList.remove('hidden');msg('Sessão encerrada.');}
document.getElementById('authMode').onclick=()=>{mode=mode==='login'?'signup':'login';document.getElementById('authTitle').textContent=mode==='signup'?'Criar primeiro acesso':'Acesso ao sistema';document.getElementById('authHelp').textContent=mode==='signup'?'Cadastre o e-mail que será usado para entrar no Napricelo Campo.':'Entre com seu e-mail e senha para acessar os dados de campo.';document.getElementById('authSubmit').textContent=mode==='signup'?'Criar acesso':'Entrar';document.getElementById('authMode').textContent=mode==='signup'?'Já tenho acesso':'Criar primeiro acesso';msg('')};
document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;msg(mode==='signup'?'Criando acesso...':'Entrando...');try{if(mode==='signup'){const d=await authRequest('signup',{email,password});if(d.access_token){saveSession(d);msg('')}else{mode='login';document.getElementById('authTitle').textContent='Confirme seu e-mail';document.getElementById('authHelp').textContent='O cadastro foi criado. Se a confirmação por e-mail estiver habilitada, confirme a mensagem recebida e depois entre normalmente.';document.getElementById('authSubmit').textContent='Entrar';document.getElementById('authMode').textContent='Criar primeiro acesso';msg('Cadastro realizado.')}}else{const d=await authRequest('token?grant_type=password',{email,password});saveSession(d);msg('')}}catch(err){msg(err.message)}};
const s=getSession();if(s?.access_token){applySession(s)}
})();