(()=>{
const AUTH_KEY='napricelo_auth_session';
const nativeFetch=window.fetch.bind(window);
let refreshPromise=null;
const css=`#authGate{position:fixed;inset:0;z-index:99999;background:#eef3f0;display:flex;align-items:center;justify-content:center;padding:20px;font-family:Arial,sans-serif}#authGate.hidden{display:none}.auth-card{width:min(420px,100%);background:#fff;border-radius:18px;padding:28px;box-shadow:0 14px 40px #0002}.auth-brand{display:flex;gap:12px;align-items:center;margin-bottom:22px}.auth-logo{width:46px;height:46px;border-radius:50%;background:#176b45;color:#fff;display:grid;place-items:center;font-weight:800;font-size:22px}.auth-brand strong{display:block;color:#176b45;font-size:20px}.auth-brand small{color:#607068}.auth-card h2{margin:0 0 6px;color:#173d2d}.auth-card p{margin:0 0 18px;color:#607068;font-size:14px;line-height:1.4}.auth-card label{display:block;font-weight:700;font-size:13px;margin:12px 0 5px}.auth-card input{box-sizing:border-box;width:100%;padding:12px;border:1px solid #cbd8d1;border-radius:9px;font-size:16px}.auth-btn{width:100%;border:0;border-radius:9px;padding:13px;margin-top:16px;background:#176b45;color:#fff;font-weight:700;cursor:pointer}.auth-msg{min-height:20px;margin-top:12px!important;font-size:13px!important;color:#6b3a32}.auth-note{margin-top:14px!important;padding:10px 12px;border-radius:9px;background:#f4f8f6;color:#52645a!important;font-size:12px!important}.auth-user{position:fixed;right:18px;top:64px;z-index:9990;background:#fff;border:1px solid #dce7e1;border-radius:9px;padding:7px 10px;font-size:12px;box-shadow:0 3px 12px #0001}.auth-user button{border:0;background:transparent;color:#176b45;font-weight:700;cursor:pointer;margin-left:8px}@media(max-width:700px){.auth-user{top:58px;right:8px}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const gate=document.createElement('div');gate.id='authGate';gate.innerHTML=`<div class="auth-card"><div class="auth-brand"><div class="auth-logo">N</div><div><strong>NAPRICELO</strong><small>Soluções Ambientais • Campo</small></div></div><h2>Acesso ao sistema</h2><p>Entre com seu e-mail e senha autorizados para acessar os dados de campo.</p><form id="authForm"><label>E-mail</label><input id="authEmail" type="email" autocomplete="username" required><label>Senha</label><input id="authPassword" type="password" autocomplete="current-password" minlength="6" required><button class="auth-btn" id="authSubmit">Entrar</button></form><p class="auth-note">A criação de novos acessos não é pública. Novos usuários devem ser autorizados pelo administrador do sistema.</p><p class="auth-msg" id="authMsg"></p></div>`;document.body.appendChild(gate);
const msg=t=>document.getElementById('authMsg').textContent=t||'';
function getSession(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function saveSession(s){localStorage.setItem(AUTH_KEY,JSON.stringify(s))}
function setAuthHeader(token){if(window.SUPABASE_HEADERS)window.SUPABASE_HEADERS.Authorization=`Bearer ${token}`;else if(typeof SUPABASE_HEADERS!=='undefined')SUPABASE_HEADERS.Authorization=`Bearer ${token}`}
function clearSession(){localStorage.removeItem(AUTH_KEY);if(window.SUPABASE_HEADERS)window.SUPABASE_HEADERS.Authorization=`Bearer ${SUPABASE_KEY}`;window.dispatchEvent(new Event('napricelo-auth-changed'))}
function loadScript(src,key){if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement('script');s.src=src;s.dataset[key]='1';document.head.appendChild(s)}
function applySession(s){if(!s?.access_token)return false;saveSession(s);setAuthHeader(s.access_token);gate.classList.add('hidden');showUser(s.user?.email||'Usuário');loadScript('secure-storage.js?v=2','secureStorage');loadScript('admin-users.js?v=1','adminUsers');loadScript('technical-record-validation.js?v=1','technicalValidation');window.dispatchEvent(new Event('napricelo-auth-changed'));return true}
function showUser(email){let box=document.getElementById('authUser');if(!box){box=document.createElement('div');box.id='authUser';box.className='auth-user';document.body.appendChild(box)}box.innerHTML=`${email}<button id="authLogout">Sair</button>`;document.getElementById('authLogout').onclick=logout}
function jwtExpMs(token){try{const p=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');const d=JSON.parse(atob(p.padEnd(Math.ceil(p.length/4)*4,'=')));return Number(d.exp||0)*1000}catch{return 0}}
function tokenPertoDeVencer(s,margemMs=120000){const exp=jwtExpMs(s?.access_token);return !exp||exp-Date.now()<=margemMs}
async function authRequest(path,body){const r=await nativeFetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||d.error_description||'Não foi possível concluir o acesso.');return d}
async function refreshSession(force=false){const atual=getSession();if(!navigator.onLine||!atual?.refresh_token)return atual;if(!force&&!tokenPertoDeVencer(atual))return atual;if(refreshPromise)return refreshPromise;refreshPromise=(async()=>{try{const d=await authRequest('token?grant_type=refresh_token',{refresh_token:atual.refresh_token});const nova={...atual,...d,app_role:atual.app_role||d.app_role};if(!nova.user&&atual.user)nova.user=atual.user;applySession(nova);return nova}catch(err){console.warn('Falha ao renovar sessão:',err);return null}finally{refreshPromise=null}})();return refreshPromise}
function isSupabaseUrl(input){try{const u=typeof input==='string'?input:input?.url||'';return !!u&&u.startsWith(SUPABASE_URL)}catch{return false}}
function isRefreshEndpoint(input){const u=typeof input==='string'?input:input?.url||'';return u.includes('/auth/v1/token')||u.includes('/auth/v1/logout')}
function comTokenAtual(input,init,token){const next={...(init||{})};const baseHeaders=init?.headers||(typeof Request!=='undefined'&&input instanceof Request?input.headers:undefined);const headers=new Headers(baseHeaders||{});if(!headers.has('apikey'))headers.set('apikey',SUPABASE_KEY);headers.set('Authorization',`Bearer ${token}`);next.headers=headers;return next}
window.fetch=async function(input,init){if(!isSupabaseUrl(input)||isRefreshEndpoint(input))return nativeFetch(input,init);let s=getSession();if(s?.refresh_token&&tokenPertoDeVencer(s)){const renovada=await refreshSession(true);if(renovada?.access_token)s=renovada}let reqInit=s?.access_token?comTokenAtual(input,init,s.access_token):init;let r=await nativeFetch(input,reqInit);if(r.status===401&&getSession()?.refresh_token){let jwtExpired=false;try{jwtExpired=(await r.clone().text()).toLowerCase().includes('jwt expired')}catch{}if(jwtExpired){const renovada=await refreshSession(true);if(renovada?.access_token){reqInit=comTokenAtual(input,init,renovada.access_token);r=await nativeFetch(input,reqInit)}}}return r};
async function validarSessao(s){if(!s?.access_token)return false;try{if(tokenPertoDeVencer(s)){const renovada=await refreshSession(true);if(!renovada?.access_token)return false;s=renovada}const r=await nativeFetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s.access_token}`}});if(!r.ok)return false;s.user=await r.json();saveSession(s);return true}catch{return false}}
async function validarAutorizacao(s){if(!s?.access_token||!s?.user?.id)return null;try{const r=await nativeFetch(`${SUPABASE_URL}/rest/v1/app_user_roles?select=perfil,ativo,nome,email&user_id=eq.${encodeURIComponent(s.user.id)}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s.access_token}`}});if(!r.ok)return null;const a=await r.json();return a?.[0]||null}catch{return null}}
async function logout(){const s=getSession();try{if(s?.access_token&&navigator.onLine)await nativeFetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s.access_token}`}})}catch{}clearSession();document.getElementById('authUser')?.remove();gate.classList.remove('hidden');msg('Sessão encerrada.')}
document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();if(!navigator.onLine)return msg('Sem internet. Para o primeiro acesso neste aparelho, conecte-se à internet.');const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,btn=document.getElementById('authSubmit');msg('Entrando...');btn.disabled=true;try{const d=await authRequest('token?grant_type=password',{email,password});const role=await validarAutorizacao(d);if(!role?.ativo)throw new Error('Este usuário não está autorizado a acessar o Napricelo Campo.');d.app_role=role;applySession(d);msg('')}catch(err){clearSession();msg(err.message)}finally{btn.disabled=false}};
window.addEventListener('online',()=>{refreshSession(true)});
setInterval(()=>{const s=getSession();if(navigator.onLine&&s?.refresh_token&&tokenPertoDeVencer(s,600000))refreshSession(true)},300000);
(async()=>{let s=getSession();if(!s?.access_token)return;if(!navigator.onLine){if(s.app_role?.ativo){applySession(s);msg('Modo offline ativo. A sessão salva neste aparelho está sendo usada.')}else msg('Sem internet e sem uma sessão autorizada salva neste aparelho.');return}if(tokenPertoDeVencer(s)){const renovada=await refreshSession(true);if(renovada?.access_token)s=renovada}if(await validarSessao(s)){s=getSession()||s;const role=await validarAutorizacao(s);if(role?.ativo){s.app_role=role;applySession(s)}else{clearSession();msg('Seu acesso está desativado ou não autorizado.')}}else{clearSession();msg('Sua sessão expirou. Entre novamente.')}})();
})();