let comercialProdutos=[],comercialOrcamentos=[],comercialItens=[];
function moeda(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function numBR(v){return Number(String(v||'0').replace(/\./g,'').replace(',','.'))||0;}
function injetarModuloComercial(){
  const grid=document.querySelector('#home .grid');
  if(grid&&!document.getElementById('cardComercial')){const b=document.createElement('button');b.id='cardComercial';b.className='card';b.setAttribute('onclick',"showPage('comercial')");b.innerHTML='<b>OR</b><span>Vendas / Orçamentos</span>';grid.insertBefore(b,grid.children[3]||null);}
  const main=document.querySelector('main');if(!main||document.getElementById('comercial'))return;
  const sec=document.createElement('section');sec.id='comercial';sec.className='page';sec.innerHTML=`<h2>Vendas e Orçamentos</h2><p>Cadastre produtos e serviços, monte propostas e transforme vendas aprovadas em agendamentos.</p>
  <div class="tabs"><button type="button" onclick="mostrarComercial('orcamento')">Novo orçamento</button><button type="button" onclick="mostrarComercial('produtos')">Produtos / serviços</button><button type="button" onclick="mostrarComercial('historico')">Orçamentos / vendas</button><button type="button" onclick="mostrarComercial('agenda')">Agenda comercial</button></div>
  <div id="comOrcamento"><form id="orcamentoForm"><h3>Novo orçamento / venda</h3><label>Cliente<select id="orcCliente" name="cliente_id" required></select></label><label>Unidade / propriedade<select id="orcUnidade" name="unidade_id"><option value="">Sem unidade</option></select></label><div class="two"><label>Data<input name="data" type="date" required></label><label>Validade (dias)<input name="validade_dias" type="number" value="15" min="1"></label></div><h3>Itens</h3><div id="orcItens"></div><button type="button" class="action" onclick="adicionarItemOrcamento()">+ Adicionar item</button><div class="two"><label>Desconto (R$)<input id="orcDesconto" name="desconto" inputmode="decimal" value="0" oninput="recalcularOrcamento()"></label><label>Acréscimos / deslocamento (R$)<input id="orcAcrescimos" name="acrescimos" inputmode="decimal" value="0" oninput="recalcularOrcamento()"></label></div><label>Forma de pagamento<input name="forma_pagamento" placeholder="Ex.: 50% entrada + 50% conclusão"></label><label>Observações / condições<textarea name="observacoes" placeholder="Materiais por conta do cliente, deslocamento, prazo, garantias..."></textarea></label><label class="check"><input type="checkbox" name="agendar_apos_aprovacao"> <span>Após aprovação, preparar agendamento do serviço</span></label><div class="autobox"><b>Total do orçamento:</b> <span id="orcTotal">R$ 0,00</span></div><button class="primary">Salvar orçamento</button></form></div>
  <div id="comProdutos" style="display:none"><form id="produtoForm"><h3>Cadastrar produto / serviço</h3><div class="two"><label>Código<input name="codigo" placeholder="Ex.: BD-1000"></label><label>Tipo<select name="tipo_item"><option>Produto</option><option>Serviço</option><option>Manutenção</option><option>Instalação</option></select></label></div><label>Nome<input name="nome" required placeholder="Ex.: Biodigestor 1.000 L"></label><div class="two"><label>Categoria<input name="categoria" placeholder="Biodigestor, SAO, Naprilimp..."></label><label>Unidade<input name="unidade" placeholder="un., serviço, kg"></label></div><label>Preço padrão (R$)<input name="preco" inputmode="decimal" required></label><label>Descrição<textarea name="descricao"></textarea></label><button class="primary">Salvar produto / serviço</button></form><h3>Produtos e serviços cadastrados</h3><div id="listaProdutosComercial"></div></div>
  <div id="comHistorico" style="display:none"><h3>Orçamentos e vendas</h3><div id="listaOrcamentosComercial"></div></div>
  <div id="comAgenda" style="display:none"><h3>Agendamentos gerados por vendas</h3><div id="listaAgendaComercial"></div></div>`;main.insertBefore(sec,document.getElementById('historico'));
  document.getElementById('orcamentoForm').addEventListener('submit',salvarOrcamentoComercial);document.getElementById('produtoForm').addEventListener('submit',salvarProdutoComercial);document.getElementById('orcCliente').addEventListener('change',preencherUnidadesOrcamento);const hoje=new Date().toISOString().slice(0,10);document.querySelector('#orcamentoForm [name=data]').value=hoje;adicionarItemOrcamento();
}
function mostrarComercial(aba){['Orcamento','Produtos','Historico','Agenda'].forEach(n=>{const el=document.getElementById('com'+n);if(el)el.style.display=n.toLowerCase()===aba?'block':'none';});if(aba==='produtos')carregarProdutosComercial();if(aba==='historico')carregarOrcamentosComercial();if(aba==='agenda')carregarAgendaComercial();}
function preencherClientesComercial(){const s=document.getElementById('orcCliente');if(!s)return;s.innerHTML='<option value="">Selecione...</option>'+clientesCache.map(c=>`<option value="${c.id}">${escHtml(c.nome)}</option>`).join('');preencherUnidadesOrcamento();}
function preencherUnidadesOrcamento(){const s=document.getElementById('orcUnidade'),cid=Number(document.getElementById('orcCliente')?.value);if(!s)return;s.innerHTML='<option value="">Sem unidade</option>'+unidadesCache.filter(u=>Number(u.cliente_id)===cid).map(u=>`<option value="${u.id}">${escHtml(u.nome)}</option>`).join('');}
async function carregarProdutosComercial(){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/produtos_servicos?select=*&ativo=eq.true&order=nome.asc`,{headers:SUPABASE_HEADERS});if(!r.ok)throw new Error(await r.text());comercialProdutos=await r.json();renderProdutosComercial();atualizarSelectsItensOrcamento();}catch(e){console.error(e);}}
function renderProdutosComercial(){const box=document.getElementById('listaProdutosComercial');if(!box)return;box.innerHTML=comercialProdutos.length?comercialProdutos.map(p=>`<div class="record"><b>${escHtml(p.nome)}</b><small>${escHtml(p.tipo_item||'')} • ${escHtml(p.categoria||'')} • ${moeda(p.preco)}</small><small>${escHtml(p.codigo||'')}${p.unidade?' • '+escHtml(p.unidade):''}</small></div>`).join(''):'<p class="muted">Nenhum produto ou serviço cadastrado.</p>';}
async function salvarProdutoComercial(e){e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const payload={codigo:o.codigo||null,nome:o.nome.trim(),categoria:o.categoria||null,tipo_item:o.tipo_item||'Produto',unidade:o.unidade||null,preco:numBR(o.preco),descricao:o.descricao||null};try{const r=await fetch(`${SUPABASE_URL}/rest/v1/produtos_servicos`,{method:'POST',headers:{...SUPABASE_HEADERS,Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());alert('Produto / serviço salvo.');e.target.reset();await carregarProdutosComercial();}catch(err){console.error(err);alert('Não foi possível salvar o produto / serviço.');}}
let seqItemOrc=0;function adicionarItemOrcamento(){const box=document.getElementById('orcItens');if(!box)return;const id=++seqItemOrc,row=document.createElement('div');row.className='autobox orc-item';row.dataset.id=id;row.innerHTML=`<label>Produto / serviço<select class="orc-prod" onchange="produtoOrcMudou(this)"><option value="">Item manual</option></select></label><label>Descrição<input class="orc-desc" required></label><div class="two"><label>Quantidade<input class="orc-qtd" type="number" step="0.001" value="1" min="0" oninput="recalcularOrcamento()"></label><label>Valor unitário (R$)<input class="orc-vu" inputmode="decimal" value="0" oninput="recalcularOrcamento()"></label></div><label>Unidade<input class="orc-un"></label><div><b>Subtotal: <span class="orc-sub">R$ 0,00</span></b> <button type="button" onclick="this.closest('.orc-item').remove();recalcularOrcamento()">Remover</button></div>`;box.appendChild(row);atualizarSelectItem(row.querySelector('.orc-prod'));}
function atualizarSelectItem(sel){const atual=sel.value;sel.innerHTML='<option value="">Item manual</option>'+comercialProdutos.map(p=>`<option value="${p.id}">${escHtml(p.nome)} — ${moeda(p.preco)}</option>`).join('');sel.value=atual;}
function atualizarSelectsItensOrcamento(){document.querySelectorAll('.orc-prod').forEach(atualizarSelectItem);}
function produtoOrcMudou(sel){const p=comercialProdutos.find(x=>Number(x.id)===Number(sel.value)),row=sel.closest('.orc-item');if(p){row.querySelector('.orc-desc').value=p.nome||'';row.querySelector('.orc-vu').value=Number(p.preco||0).toFixed(2).replace('.',',');row.querySelector('.orc-un').value=p.unidade||'';}recalcularOrcamento();}
function recalcularOrcamento(){let total=0;document.querySelectorAll('.orc-item').forEach(r=>{const sub=(Number(r.querySelector('.orc-qtd').value)||0)*numBR(r.querySelector('.orc-vu').value);total+=sub;r.querySelector('.orc-sub').textContent=moeda(sub);});total=total-numBR(document.getElementById('orcDesconto')?.value)+numBR(document.getElementById('orcAcrescimos')?.value);document.getElementById('orcTotal').textContent=moeda(total);return total;}
async function salvarOrcamentoComercial(e){e.preventDefault();const f=e.target,o=Object.fromEntries(new FormData(f)),cl=clientesCache.find(c=>Number(c.id)===Number(o.cliente_id)),un=unidadesCache.find(u=>Number(u.id)===Number(o.unidade_id));const itens=[...document.querySelectorAll('.orc-item')].map(r=>({produto_id:Number(r.querySelector('.orc-prod').value)||null,descricao:r.querySelector('.orc-desc').value.trim(),quantidade:Number(r.querySelector('.orc-qtd').value)||0,unidade:r.querySelector('.orc-un').value||null,valor_unitario:numBR(r.querySelector('.orc-vu').value)})).filter(x=>x.descricao&&x.quantidade>0);if(!itens.length)return alert('Inclua pelo menos um item.');const total=recalcularOrcamento(),numero=`ORC-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;const payload={numero,cliente_id:cl?.id||null,unidade_id:un?.id||null,cliente:cl?.nome||null,unidade:un?.nome||null,municipio:un?.municipio||cl?.municipio||null,data:o.data,validade_dias:Number(o.validade_dias)||15,status:'Em elaboração',desconto:numBR(o.desconto),acrescimos:numBR(o.acrescimos),total,forma_pagamento:o.forma_pagamento||null,observacoes:o.observacoes||null,agendar_apos_aprovacao:!!o.agendar_apos_aprovacao};try{let r=await fetch(`${SUPABASE_URL}/rest/v1/orcamentos`,{method:'POST',headers:{...SUPABASE_HEADERS,Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());const orc=(await r.json())[0];const its=itens.map(x=>({...x,orcamento_id:orc.id,subtotal:x.quantidade*x.valor_unitario}));r=await fetch(`${SUPABASE_URL}/rest/v1/orcamento_itens`,{method:'POST',headers:{...SUPABASE_HEADERS,Prefer:'return=minimal'},body:JSON.stringify(its)});if(!r.ok)throw new Error(await r.text());alert(`Orçamento ${numero} salvo.`);f.reset();document.querySelector('#orcamentoForm [name=data]').value=new Date().toISOString().slice(0,10);document.getElementById('orcItens').innerHTML='';adicionarItemOrcamento();recalcularOrcamento();mostrarComercial('historico');}catch(err){console.error(err);alert('Não foi possível salvar o orçamento.');}}
async function carregarOrcamentosComercial(){const box=document.getElementById('listaOrcamentosComercial');if(box)box.innerHTML='<p>Carregando...</p>';try{const r=await fetch(`${SUPABASE_URL}/rest/v1/orcamentos?select=*&order=created_at.desc`,{headers:SUPABASE_HEADERS});if(!r.ok)throw new Error(await r.text());comercialOrcamentos=await r.json();renderOrcamentosComercial();}catch(e){console.error(e);if(box)box.innerHTML='<p>Não foi possível carregar.</p>';}}
function renderOrcamentosComercial(){const box=document.getElementById('listaOrcamentosComercial');if(!box)return;box.innerHTML=comercialOrcamentos.length?comercialOrcamentos.map(o=>`<div class="record"><b>${escHtml(o.numero||'Orçamento')} • ${escHtml(o.cliente||'')}</b><small>${fmtComData(o.data)} • ${moeda(o.total)} • ${escHtml(o.status||'')}</small><div class="mini-actions"><button onclick="alterarStatusOrc(${o.id},'Aprovado')">Aprovar</button><button onclick="alterarStatusOrc(${o.id},'Venda fechada')">Venda fechada</button><button onclick="agendarOrcamento(${o.id})">Agendar</button><button onclick="verOrcamentoComercial(${o.id})">Ver</button></div></div>`).join(''):'<p class="muted">Nenhum orçamento salvo.</p>';}
function fmtComData(v){if(!v)return '—';const[a,m,d]=String(v).slice(0,10).split('-');return `${d}/${m}/${a}`;}
async function alterarStatusOrc(id,status){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/orcamentos?id=eq.${Number(id)}`,{method:'PATCH',headers:{...SUPABASE_HEADERS,Prefer:'return=minimal'},body:JSON.stringify({status})});if(!r.ok)throw new Error(await r.text());await carregarOrcamentosComercial();}catch(e){console.error(e);alert('Não foi possível atualizar o status.');}}
async function verOrcamentoComercial(id){const o=comercialOrcamentos.find(x=>Number(x.id)===Number(id));if(!o)return;try{const r=await fetch(`${SUPABASE_URL}/rest/v1/orcamento_itens?select=*&orcamento_id=eq.${id}&order=id.asc`,{headers:SUPABASE_HEADERS});const itens=await r.json();abrirFicha(`<div class="detail-head"><small>ORÇAMENTO / VENDA</small><h2>${escHtml(o.numero||'')}</h2><p>${escHtml(o.cliente||'')}</p></div>${linha('Unidade',o.unidade)}${linha('Data',fmtComData(o.data))}${linha('Status',o.status)}<h3>Itens</h3>${itens.map(i=>`<div class="detail-row"><b>${escHtml(i.descricao)}</b><span>${i.quantidade} ${escHtml(i.unidade||'')} × ${moeda(i.valor_unitario)} = <b>${moeda(i.subtotal)}</b></span></div>`).join('')}<h3>Total</h3>${linha('Desconto',moeda(o.desconto))}${linha('Acréscimos',moeda(o.acrescimos))}${linha('TOTAL',moeda(o.total))}${linha('Pagamento',o.forma_pagamento)}<div class="detail-note">${escHtml(o.observacoes||'Sem observações.')}</div>`);}catch(e){console.error(e);}}
async function agendarOrcamento(id){const o=comercialOrcamentos.find(x=>Number(x.id)===Number(id));if(!o)return;const data=prompt('Data do serviço (AAAA-MM-DD):',new Date().toISOString().slice(0,10));if(!data)return;const hora=prompt('Horário (HH:MM):','08:00');const tipo=prompt('Tipo de serviço:','Instalação / manutenção');if(!tipo)return;const payload={orcamento_id:o.id,cliente_id:o.cliente_id,unidade_id:o.unidade_id,cliente:o.cliente,unidade:o.unidade,tipo_servico:tipo,data_agendada:data,horario:hora||null,local_servico:o.unidade||null,status:'Agendado'};try{const r=await fetch(`${SUPABASE_URL}/rest/v1/agendamentos_servicos`,{method:'POST',headers:{...SUPABASE_HEADERS,Prefer:'return=minimal'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());alert('Serviço agendado.');mostrarComercial('agenda');}catch(e){console.error(e);alert('Não foi possível agendar.');}}
async function carregarAgendaComercial(){const box=document.getElementById('listaAgendaComercial');if(box)box.innerHTML='<p>Carregando...</p>';try{const r=await fetch(`${SUPABASE_URL}/rest/v1/agendamentos_servicos?select=*&status=eq.Agendado&order=data_agendada.asc,horario.asc`,{headers:SUPABASE_HEADERS});const a=await r.json();box.innerHTML=a.length?a.map(x=>`<div class="record"><b>${escHtml(x.tipo_servico||'Serviço')} • ${escHtml(x.cliente||'')}</b><small>${fmtComData(x.data_agendada)}${x.horario?' • '+String(x.horario).slice(0,5):''}${x.unidade?' • '+escHtml(x.unidade):''}</small><button onclick="concluirAgendaComercial(${x.id})">Concluir</button></div>`).join(''):'<p class="muted">Nenhum serviço agendado.</p>';}catch(e){console.error(e);if(box)box.innerHTML='<p>Não foi possível carregar.</p>';}}
async function concluirAgendaComercial(id){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/agendamentos_servicos?id=eq.${Number(id)}`,{method:'PATCH',headers:{...SUPABASE_HEADERS,Prefer:'return=minimal'},body:JSON.stringify({status:'Concluído'})});if(!r.ok)throw new Error(await r.text());carregarAgendaComercial();}catch(e){console.error(e);}}
(function initComercial(){injetarModuloComercial();setTimeout(async()=>{if(!clientesCache.length)await carregarClientesUnidades();preencherClientesComercial();await carregarProdutosComercial();},800);const base=window.showPage;window.showPage=function(id){base(id);if(id==='comercial'){preencherClientesComercial();carregarProdutosComercial();}};})();