(function(){
function escC(v){return typeof escEq==='function'?escEq(v):String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function fmtC(v){try{return typeof fmtData==='function'?fmtData(v):String(v||'')}catch(_){return String(v||'')}}
async function get(path){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:SUPABASE_HEADERS});if(!r.ok)throw new Error(await r.text());return r.json()}
function fotosDaManutencao(m){return [['Antes',m.foto_antes_url||m.foto_antes],['Durante',m.foto_durante_url||m.foto_durante],['Depois',m.foto_depois_url||m.foto_depois]].filter(x=>x[1]).map(([rot,u])=>({rot,u}))}
function osDaManutencao(m,oss){const mid=Number(m.id||0);return oss.find(o=>Number(o.manutencao_id||0)===mid)||oss.find(o=>{const a=String(o.observacoes||o.observacao||'');return mid&&a.includes(String(mid))})||null}
function blocoFotos(m,oss){const fotos=fotosDaManutencao(m);if(!fotos.length)return '';
 const os=osDaManutencao(m,oss);const num=os?(os.numero||`OS-${String(os.id||'').padStart(5,'0')}`):'';const resp=m.responsavel_tecnico||m.responsavel||m.tecnico||'';const titulo=num?`Manutenção • ${escC(num)}`:'Manutenção registrada';
 return `<section class="equip-photo-event"><div class="equip-photo-event-head"><div><b>${titulo}</b><span>${fmtC(m.data||m.created_at)}${resp?' • '+escC(resp):''}</span></div>${os&&Number(os.agenda_id||0)?`<div><button onclick="fecharFichaEquipamento();executarAgendaComercial(${Number(os.agenda_id)})">Abrir OS</button><button onclick="imprimirOrdemServico(${Number(os.agenda_id)})">PDF</button></div>`:''}</div><div class="equip-photo-grid">${fotos.map(f=>`<figure><div class="equip-photo-label">${escC(f.rot)}</div><img src="${escC(f.u)}" alt="${escC(f.rot)}"><figcaption>${fmtC(m.data||m.created_at)}</figcaption></figure>`).join('')}</div></section>`}
async function carregarCentralEquipamento(id){
  const content=document.getElementById('equipProfileContent');if(!content)return;
  let host=document.getElementById('equipCentralExtra');if(host)host.remove();host=document.createElement('section');host.id='equipCentralExtra';host.className='equip-central-extra';host.innerHTML='<p class="muted">Carregando histórico operacional completo...</p>';content.appendChild(host);
  try{
    const [manut,analises,oss,inst]=await Promise.all([
      get(`manutencoes?select=*&equipamento_id=eq.${Number(id)}&order=created_at.desc`),
      get(`analises?select=*&equipamento_id=eq.${Number(id)}&order=created_at.desc`),
      get(`ordens_servico?select=*&equipamento_id=eq.${Number(id)}&order=id.desc`),
      get('instalacoes?select=*&order=created_at.desc')
    ]);
    const instalacoes=inst.filter(x=>Number(x.equipamento_id)===Number(id));
    const totalFotos=manut.reduce((n,m)=>n+fotosDaManutencao(m).length,0);const manutComFotos=manut.filter(m=>fotosDaManutencao(m).length);
    host.innerHTML=`
      <div class="equip-central-stats"><div><b>${oss.length}</b><span>OS vinculadas</span></div><div><b>${instalacoes.length}</b><span>Instalações</span></div><div><b>${totalFotos}</b><span>Fotos</span></div><div><b>${manut.length+analises.length}</b><span>Registros técnicos</span></div></div>
      <h3>Ordens de Serviço do equipamento</h3>${oss.length?`<div class="equip-central-list">${oss.map(o=>{const agenda=Number(o.agenda_id||0),num=o.numero||`OS-${String(o.id||'').padStart(5,'0')}`;return `<div class="equip-central-card"><div><b>${escC(num)}</b><span>${escC(o.status||'Aberta')} • ${fmtC(o.data_fim||o.data_inicio||o.created_at)}</span><small>${escC(o.responsavel_execucao||'A definir')}</small></div><div>${agenda?`<button onclick="fecharFichaEquipamento();executarAgendaComercial(${agenda})">Abrir OS</button><button onclick="imprimirOrdemServico(${agenda})">PDF</button>`:''}</div></div>`}).join('')}</div>`:'<p class="muted">Nenhuma ordem de serviço vinculada diretamente a este equipamento.</p>'}
      <h3>Instalações vinculadas</h3>${instalacoes.length?`<div class="equip-central-list">${instalacoes.map(x=>`<div class="equip-central-card"><div><b>${escC(x.produto||'Instalação')}</b><span>${fmtC(x.data||x.created_at)}${x.volume?' • '+escC(x.volume):''}</span><small>${escC(x.local_instalacao||'')}</small></div><div><button onclick="abrirInstalacaoPorId(${Number(x.id)})">Ver POP</button>${typeof gerarRelatorioInstalacao==='function'?`<button onclick="gerarRelatorioInstalacao(${Number(x.id)})">PDF</button>`:''}</div></div>`).join('')}</div>`:'<p class="muted">Nenhuma instalação vinculada diretamente a este equipamento.</p>'}
      <h3>Registro fotográfico por atendimento</h3>${manutComFotos.length?`<div class="equip-photo-history">${manutComFotos.map(m=>blocoFotos(m,oss)).join('')}</div>`:'<p class="muted">Nenhuma foto vinculada às manutenções deste equipamento.</p>'}
      <h3>Documentos e relatórios</h3><div class="equip-doc-actions"><button onclick="document.getElementById('equipHistory')?.scrollIntoView({behavior:'smooth'})">Histórico técnico</button>${oss.length&&Number(oss[0].agenda_id||0)?`<button onclick="imprimirOrdemServico(${Number(oss[0].agenda_id)})">Última OS / PDF</button>`:''}${instalacoes.length?`<button onclick="gerarRelatorioInstalacao(${Number(instalacoes[0].id)})">Última instalação / PDF</button>`:''}</div>`;
  }catch(e){console.error('Central do equipamento',e);host.innerHTML='<p class="muted">Não foi possível carregar o histórico operacional completo deste equipamento.</p>'}
}
const base=window.abrirFichaEquipamento;if(typeof base==='function')window.abrirFichaEquipamento=function(id){const r=base.apply(this,arguments);setTimeout(()=>carregarCentralEquipamento(id),100);return r};
const st=document.createElement('style');st.textContent=`.equip-central-extra{margin-top:18px}.equip-central-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0 16px}.equip-central-stats div{background:#eef6f2;border:1px solid #dbe8e1;border-radius:10px;padding:10px;text-align:center}.equip-central-stats b{display:block;color:#176b45;font-size:20px}.equip-central-stats span{font-size:11px;color:#65746c}.equip-central-list{display:grid;gap:7px}.equip-central-card{display:flex;justify-content:space-between;gap:12px;align-items:center;border:1px solid #dce7e1;border-left:4px solid #176b45;border-radius:8px;padding:10px;background:#fff}.equip-central-card b,.equip-central-card span,.equip-central-card small{display:block}.equip-central-card span,.equip-central-card small{color:#65746c;margin-top:2px}.equip-central-card button,.equip-doc-actions button,.equip-photo-event-head button{border:0;border-radius:7px;padding:8px 10px;background:#edf6f1;color:#176b45;font-weight:700;margin-left:5px}.equip-photo-history{display:grid;gap:14px}.equip-photo-event{border:1px solid #dce7e1;border-radius:10px;padding:10px;background:#fdfefd}.equip-photo-event-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:9px;padding-bottom:8px;border-bottom:1px solid #e4ece8}.equip-photo-event-head b,.equip-photo-event-head span{display:block}.equip-photo-event-head b{color:#176b45}.equip-photo-event-head span{font-size:11px;color:#65746c;margin-top:2px}.equip-photo-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.equip-photo-grid figure{margin:0;border:1px solid #dce7e1;border-radius:8px;padding:6px;background:#fff;position:relative}.equip-photo-grid img{width:100%;height:150px;object-fit:contain}.equip-photo-grid figcaption{text-align:center;font-size:10px;color:#5f6f66;margin-top:4px}.equip-photo-label{font-size:11px;font-weight:800;color:#176b45;text-align:center;padding:4px 0 6px}.equip-doc-actions{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px}.equip-doc-actions button{margin-left:0}@media(max-width:700px){.equip-central-stats{grid-template-columns:1fr 1fr}.equip-central-card,.equip-photo-event-head{align-items:flex-start;flex-direction:column}.equip-photo-grid{grid-template-columns:1fr}.equip-central-card button,.equip-photo-event-head button{margin-left:0;margin-right:5px}.equip-photo-grid img{height:220px}}`;document.head.appendChild(st);
})();