function escEq(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function tipoPaginaManut(tipo){const t=String(tipo||"").toLowerCase();if(t.includes("gordura"))return "gordura";if(t==="sao"||t.includes("água e óleo")||t.includes("agua e oleo"))return "sao";return "biodigestor";}
function acharIndiceEquip(id){return eqs().findIndex(e=>Number(e.id)===Number(id));}
function linksAnaliseEquip(a){const obs=String(a?.observacoes||'');const foto=a?.foto_url||(obs.match(/(?:^|\n|\s)Foto:\s*(https?:\/\/\S+)/i)||[])[1]||null;const laudo=a?.laudo_url||(obs.match(/(?:^|\n|\s)Laudo:\s*(https?:\/\/\S+)/i)||[])[1]||null;const limpa=obs.replace(/(?:^|\n|\s)Foto:\s*https?:\/\/\S+/ig,' ').replace(/(?:^|\n|\s)Laudo:\s*https?:\/\/\S+/ig,' ').replace(/\s+/g,' ').trim();return{foto,laudo,limpa};}
window.abrirAnexoAnaliseEquip=function(url){if(url)window.open(url,'_blank','noopener');};
window.verDetalhesAnaliseEquip=function(id){const a=(window.clienteFichaCache?.analises||[]).find(x=>Number(x.id)===Number(id));if(!a)return alert('Análise não encontrada.');const l=linksAnaliseEquip(a);if(typeof window.mostrarDetalhesAnalise==='function')return window.mostrarDetalhesAnalise(a,l);alert(`Análise ${a.codigo||''}\nData: ${fmtData(a.data||a.created_at)}\nPonto: ${a.ponto||'—'}\nResponsável: ${a.responsavel||'—'}\npH: ${a.ph??'—'}\nTemperatura: ${a.temperatura??'—'}\nDBO: ${a.dbo??'—'}\nDQO: ${a.dqo??'—'}\n${l.limpa||''}`);};
window.imprimirAnaliseEquip=function(id){const a=(window.clienteFichaCache?.analises||[]).find(x=>Number(x.id)===Number(id));if(!a)return alert('Análise não encontrada.');const l=linksAnaliseEquip(a);if(typeof window.imprimirAnaliseAmbiental==='function')return window.imprimirAnaliseAmbiental({...a,observacoes:l.limpa});alert('Relatório da análise ainda não está disponível.');};
function abrirFichaEquipamento(id){
  const e=clienteFichaCache.equip.find(x=>Number(x.id)===Number(id))||eqs().find(x=>Number(x.id)===Number(id));if(!e)return;
  const manut=clienteFichaCache.manut.filter(x=>Number(x.equipamento_id)===Number(e.id));
  const analises=clienteFichaCache.analises.filter(x=>Number(x.equipamento_id)===Number(e.id));
  const unidade=(typeof unidadesCache!=="undefined"?unidadesCache:[]).find(u=>Number(u.id)===Number(e.unidade_id));
  const cliente=(typeof clientesCache!=="undefined"?clientesCache:[]).find(c=>Number(c.id)===Number(e.cliente_id));
  const st=typeof statusPeriodicidade==="function"?statusPeriodicidade(e):{classe:"sem-periodo",texto:"Periodicidade não definida"};
  const stA=typeof statusPeriodicidadeAnalise==="function"?statusPeriodicidadeAnalise(e):{classe:"sem-periodo",texto:"Periodicidade de análise não definida"};
  const ultimaExibida=manut[0]?fmtData(manut[0].data||manut[0].created_at):(e.data_base_manutencao&&typeof fmtPeriodoData==='function'?fmtPeriodoData(e.data_base_manutencao):"—");
  const rotuloUltima=manut[0]?"Última manutenção":"Data-base informada";
  const ultimaAnaliseExibida=analises[0]?fmtData(analises[0].data||analises[0].created_at):(e.data_base_analise&&typeof fmtPeriodoData==='function'?fmtPeriodoData(e.data_base_analise):"—");
  const rotuloUltimaAnalise=analises[0]?"Última análise":"Data-base da análise";
  let modal=document.getElementById("equipProfileModal");
  if(!modal){modal=document.createElement("div");modal.id="equipProfileModal";modal.className="detail-modal";modal.innerHTML='<div class="detail-sheet equip-profile-sheet"><button class="detail-close" onclick="fecharFichaEquipamento()">×</button><div id="equipProfileContent"></div></div>';document.body.appendChild(modal);}
  document.getElementById("equipProfileContent").innerHTML=`
    <div class="detail-head"><small>FICHA DO EQUIPAMENTO</small><h2>${escEq(e.codigo||"Sem código")}</h2><p>${escEq(e.tipo||"")}${e.capacidade?" • "+escEq(e.capacidade):""}</p></div>
    <div class="equip-actions"><button onclick="iniciarManutencaoEquip(${e.id})">Nova manutenção</button><button onclick="iniciarAnaliseEquip(${e.id})">Nova análise</button><button onclick="document.getElementById('equipHistory').scrollIntoView({behavior:'smooth'})">Histórico completo</button></div>
    <div class="period-card ${escEq(st.classe)}"><div><b>Controle de periodicidade</b><span>${e.periodicidade_meses?`A cada ${e.periodicidade_meses} mês(es)`:"Não definida"}</span></div><div><b>Próxima manutenção</b><span>${typeof fmtPeriodoData==="function"?fmtPeriodoData(e.proxima_manutencao):(e.proxima_manutencao||"—")}</span></div><div class="period-status">${escEq(st.texto)}</div><button onclick="definirPeriodicidadeEquipamento(${e.id})">Alterar periodicidade</button></div>
    <div class="period-card ${escEq(stA.classe)}"><div><b>Controle de análises</b><span>${e.periodicidade_analise_meses?`A cada ${e.periodicidade_analise_meses} mês(es)`:"Não definida"}</span></div><div><b>Próxima análise</b><span>${typeof fmtPeriodoData==="function"?fmtPeriodoData(e.proxima_analise):(e.proxima_analise||"—")}</span></div><div class="period-status">${escEq(stA.texto)}</div><button onclick="definirPeriodicidadeAnalise(${e.id})">Alterar periodicidade</button></div>
    <div class="profile-info-grid"><div><b>Cliente</b><span>${escEq(cliente?.nome||e.cliente||"—")}</span></div><div><b>Unidade</b><span>${escEq(unidade?.nome||e.unidade||"—")}</span></div><div><b>Município</b><span>${escEq(e.municipio||unidade?.municipio||cliente?.municipio||"—")}</span></div><div><b>Localização / setor</b><span>${escEq(e.localizacao||"—")}</span></div><div><b>Marca / modelo</b><span>${escEq(e.modelo||"—")}</span></div><div><b>Capacidade</b><span>${escEq(e.capacidade||"—")}</span></div></div>
    <div class="profile-stats"><div><b>${manut.length}</b><span>Manutenções</span></div><div><b>${analises.length}</b><span>Análises</span></div><div><b>${ultimaExibida}</b><span>${rotuloUltima}</span></div><div><b>${ultimaAnaliseExibida}</b><span>${rotuloUltimaAnalise}</span></div></div>
    ${e.data_base_manutencao&&!manut.length?`<div class="detail-note">Data-base informada para programação: <b>${fmtPeriodoData(e.data_base_manutencao)}</b>. Ela será substituída automaticamente pela próxima manutenção registrada no aplicativo.</div>`:""}
    ${e.data_base_analise&&!analises.length?`<div class="detail-note">Data-base informada para análises: <b>${fmtPeriodoData(e.data_base_analise)}</b>. Ela será substituída automaticamente pela próxima análise registrada no aplicativo.</div>`:""}
    ${e.observacoes?`<h3>Observações do equipamento</h3><div class="detail-note">${escEq(e.observacoes)}</div>`:""}
    <h3 id="equipHistory">Histórico completo</h3>${historicoEquipHtml(manut,analises)}
  `;
  modal.classList.add("open");document.body.style.overflow="hidden";
}
function fecharFichaEquipamento(){const m=document.getElementById("equipProfileModal");if(m)m.classList.remove("open");document.body.style.overflow="hidden";}
function historicoEquipHtml(manut,analises){
  const itens=[...manut.map(x=>({...x,_cat:"Manutenção",_data:x.data||x.created_at})),...analises.map(x=>({...x,_cat:"Análise",_data:x.data||x.created_at}))].sort((a,b)=>new Date(b._data)-new Date(a._data));
  if(!itens.length)return '<p class="muted">Nenhuma manutenção ou análise registrada para este equipamento.</p>';
  return `<div class="equip-history">${itens.map(x=>{if(x._cat==='Análise'){const l=linksAnaliseEquip(x);const obs=l.limpa?`<p>${escEq(l.limpa)}</p>`:'';const acoes=`<div class="equip-history-actions"><button type="button" onclick="verDetalhesAnaliseEquip(${Number(x.id)})">Ver detalhes</button>${l.foto?`<button type="button" onclick="abrirAnexoAnaliseEquip('${escEq(l.foto)}')">Foto</button>`:''}${l.laudo?`<button type="button" onclick="abrirAnexoAnaliseEquip('${escEq(l.laudo)}')">Laudo</button>`:''}<button type="button" onclick="imprimirAnaliseEquip(${Number(x.id)})">PDF</button></div>`;return `<div><div><b>Análise</b><span>${fmtData(x._data)}</span></div><small>${x.responsavel?"Responsável: "+escEq(x.responsavel):""}${x.ponto?" • Ponto: "+escEq(x.ponto):""}</small>${obs}${acoes}</div>`;}return `<div><div><b>${escEq(x._cat)}</b><span>${fmtData(x._data)}</span></div><small>${x.tecnico?"Responsável: "+escEq(x.tecnico):x.responsavel?"Responsável: "+escEq(x.responsavel):""}${x.ponto?" • Ponto: "+escEq(x.ponto):""}</small>${x.observacoes?`<p>${escEq(x.observacoes)}</p>`:""}</div>`;}).join("")}</div>`;
}
function prepararSelecaoEquip(page,id){fecharFichaEquipamento();fecharFichaCliente();showPage(page);refreshEquipSelectors();const idx=acharIndiceEquip(id);if(idx<0)return alert("Equipamento não encontrado na lista atual.");setTimeout(()=>{const sel=page==="analise"?document.getElementById("analiseEquip"):document.querySelector(`#${page} .equipSelect`);if(sel){sel.value=String(idx);sel.dispatchEvent(new Event("change",{bubbles:true}));sel.scrollIntoView({behavior:"smooth",block:"center"});}},100);}
function iniciarManutencaoEquip(id){const e=clienteFichaCache.equip.find(x=>Number(x.id)===Number(id))||eqs().find(x=>Number(x.id)===Number(id));if(!e)return;prepararSelecaoEquip(tipoPaginaManut(e.tipo),id);}
function iniciarAnaliseEquip(id){prepararSelecaoEquip("analise",id);}
const cartaoEquipClienteBase=window.cartaoEquipCliente;
window.cartaoEquipCliente=function(e,manut,analises){const ms=manut.filter(x=>Number(x.equipamento_id)===Number(e.id));const as=analises.filter(x=>Number(x.equipamento_id)===Number(e.id));const ultimaM=ms[0],ultimaA=as[0];const st=typeof statusPeriodicidade==="function"?statusPeriodicidade(e):null;const stA=typeof statusPeriodicidadeAnalise==="function"?statusPeriodicidadeAnalise(e):null;const baseInfo=!ultimaM&&e.data_base_manutencao?`Data-base: <b>${fmtPeriodoData(e.data_base_manutencao)}</b>`:"Sem manutenção registrada";const baseA=!ultimaA&&e.data_base_analise?`Data-base análise: <b>${fmtPeriodoData(e.data_base_analise)}</b>`:"";return `<div class="profile-equip clickable-equip" onclick="abrirFichaEquipamento(${e.id})"><div class="profile-equip-main"><b>${escEq(e.codigo||"Sem código")}</b><span>${escEq(e.tipo||"")}${e.capacidade?" • "+escEq(e.capacidade):""}</span><small>${escEq(e.localizacao||"")}${e.modelo?" • "+escEq(e.modelo):""}</small></div><div class="profile-equip-meta"><span>${ms.length} manut.</span><span>${as.length} análises</span>${st?`<span class="status-mini ${escEq(st.classe)}">${escEq(st.texto)}</span>`:""}${stA?`<span class="status-mini ${escEq(stA.classe)}">${escEq(stA.texto)}</span>`:""}</div><div class="profile-last">${ultimaM?`Última manutenção: <b>${fmtData(ultimaM.data||ultimaM.created_at)}</b>`:baseInfo}${e.proxima_manutencao?`<br>Próxima manutenção: <b>${fmtPeriodoData(e.proxima_manutencao)}</b>`:""}${ultimaA?`<br>Última análise: <b>${fmtData(ultimaA.data||ultimaA.created_at)}</b>`:baseA?`<br>${baseA}`:""}${e.proxima_analise?`<br>Próxima análise: <b>${fmtPeriodoData(e.proxima_analise)}</b>`:""}<br><span class="open-hint">Toque para abrir a ficha do equipamento</span></div></div>`;};
(function(){const st=document.createElement('style');st.textContent='.equip-history-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.equip-history-actions button{border:0;border-radius:7px;padding:7px 9px;background:#edf6f1;color:#176b45;font-weight:700}';document.head.appendChild(st);})();