const CONFIG_INSTALACAO={
  'Biodigestor':{checks:['Produto e capacidade conferidos','Local e cota de instalação conferidos','Base/nivelamento em condição adequada','Tubulação de entrada instalada e verificada','Tubulação de saída instalada e verificada','Respiro/ventilação verificado','Dispositivo/saída de lodo acessível','Estanqueidade e ausência de vazamentos verificadas','Fluxo hidráulico testado','Tampas e acessos em condição adequada','Destino final do efluente conferido'],extras:[]},
  'Fossa séptica':{checks:['Produto e capacidade conferidos','Distâncias e local de implantação conferidos','Base/nivelamento em condição adequada','Entrada e saída instaladas nas cotas previstas','Ventilação sanitária verificada','Estanqueidade verificada','Tampas de inspeção acessíveis','Fluxo hidráulico testado','Destino final/sumidouro conferido','Área sinalizada e protegida'],extras:[]},
  'Caixa de gordura':{checks:['Caixa e capacidade conferidas','Posição antes do tratamento principal conferida','Base/nivelamento adequado','Entrada e saída instaladas corretamente','Sifonamento/fecho hídrico verificado quando aplicável','Tampa acessível para limpeza','Estanqueidade verificada','Fluxo hidráulico testado','Ausência de retorno/vazamento','Orientação de limpeza repassada ao cliente'],extras:[]},
  'Caixa separadora de água e óleo':{checks:['Sistema e capacidade conferidos','Caixa de areia/pré-tratamento conferida','Base/nivelamento adequado','Entrada do efluente do lavador/oficina conferida','Compartimentos internos e interligações verificados','Saída do efluente instalada e identificada','Estanqueidade verificada','Fluxo hidráulico testado','Acesso para retirada de lama e óleo garantido','Destino do efluente final conferido','Orientação de manutenção repassada ao cliente'],extras:[{n:'pre_tratamento',l:'Pré-tratamento / caixa de areia',p:'Ex.: caixa de areia, cisterna, gradeamento'}]},
  'Sistema para Queijeira':{checks:['Fluxograma do sistema conferido','Caixa gradeada/pré-tratamento instalada','Caixa de gordura instalada quando prevista','Equalizador instalado e nivelado','Reator/Ecobio instalado e interligado','Filtro instalado e acessível','Caixa de inspeção/cloração instalada quando prevista','Tubulações por gravidade e cotas verificadas','Estanqueidade dos componentes verificada','Teste de fluxo completo realizado','Destino final do efluente conferido','Orientações operacionais repassadas ao cliente'],extras:[{n:'vol_caixa_gradeada',l:'Caixa gradeada / pré-tratamento',p:'Ex.: 300 L'},{n:'vol_caixa_gordura',l:'Caixa de gordura',p:'Ex.: 120 L'},{n:'vol_equalizador',l:'Equalizador',p:'Ex.: 2.500 L'},{n:'vol_reator',l:'Reator / Ecobio',p:'Ex.: 2.500 L'},{n:'vol_filtro',l:'Filtro',p:'Ex.: 220 L'},{n:'vol_clorador',l:'Inspeção / clorador',p:'Ex.: 48 L'},{n:'destino_final',l:'Destino final',p:'Ex.: sumidouro, vala de infiltração'}]}
};
function preencherClientesInstalacao(){const c=document.getElementById('instClienteSelect'),u=document.getElementById('instUnidadeSelect');if(!c||!u)return;c.innerHTML='<option value="">Selecione...</option>'+clientesCache.map(x=>`<option value="${x.id}">${escHtml(x.nome)}</option>`).join('');preencherUnidadesInstalacao();}
function preencherUnidadesInstalacao(){const c=document.getElementById('instClienteSelect'),u=document.getElementById('instUnidadeSelect');if(!c||!u)return;const cid=Number(c.value);const us=unidadesCache.filter(x=>Number(x.cliente_id)===cid);u.innerHTML='<option value="">Sem unidade</option>'+us.map(x=>`<option value="${x.id}">${escHtml(x.nome)}</option>`).join('');const cl=clientesCache.find(x=>Number(x.id)===cid);if(cl)document.getElementById('instMunicipio').value=cl.municipio||'';}
function aplicarUnidadeInstalacao(){const u=unidadesCache.find(x=>Number(x.id)===Number(document.getElementById('instUnidadeSelect')?.value));if(u?.municipio)document.getElementById('instMunicipio').value=u.municipio;}
function produtoInstalacaoMudou(){const p=document.getElementById('instProduto')?.value||'Biodigestor',cfg=CONFIG_INSTALACAO[p]||CONFIG_INSTALACAO.Biodigestor;const lab=document.getElementById('instVolumeLabel');if(lab)lab.firstChild.textContent=p==='Sistema para Queijeira'?'Capacidade / vazão geral do sistema':'Volume / capacidade';const ex=document.getElementById('instProdutoExtras');if(ex)ex.innerHTML=cfg.extras.length?`<h3>Componentes / volumes do sistema</h3><div class="two">${cfg.extras.map(x=>`<label>${x.l}<input name="${x.n}" placeholder="${x.p}"></label>`).join('')}</div>`:'';const ch=document.getElementById('instChecklist');if(ch)ch.innerHTML=cfg.checks.map(x=>`<label class="check"><input type="checkbox" data-check="${escHtml(x)}"> <span>${escHtml(x)}</span></label>`).join('');}
function componentesInstalacao(fd){const nomes=['pre_tratamento','vol_caixa_gradeada','vol_caixa_gordura','vol_equalizador','vol_reator','vol_filtro','vol_clorador','destino_final'];return nomes.map(n=>({campo:n,valor:String(fd.get(n)||'').trim()})).filter(x=>x.valor);}
async function salvarInstalacao(form){const fd=new FormData(form),o=Object.fromEntries([...fd.entries()].filter(([,v])=>!(v instanceof File)));const cl=clientesCache.find(x=>Number(x.id)===Number(o.cliente_id)),un=unidadesCache.find(x=>Number(x.id)===Number(o.unidade_id));const checks=[...form.querySelectorAll('input[type="checkbox"][data-check]')].map(x=>({item:x.dataset.check,ok:x.checked}));const files=[...form.querySelectorAll('input[type="file"]')],fotos={};const btn=form.querySelector('button.primary');const agendamentoId=o.agendamento_id?Number(o.agendamento_id):null;
  try{if(btn){btn.disabled=true;btn.textContent='Sincronizando fotos e salvando instalação...';}const etapas=['antes','durante','depois'];for(let i=0;i<files.length;i++){
      files[i].dataset.etapa=etapas[i];let url=files[i].dataset.cloudUrl||null;
      if(window.NAP_PHOTO_AUTOSAVE?.ensureUploaded){try{url=await window.NAP_PHOTO_AUTOSAVE.ensureUploaded(files[i],`INST-${agendamentoId||cl?.id||Date.now()}`)||url;}catch(e){console.warn('Falha ao sincronizar foto da instalação',e);}}
      if(!url&&files[i].files?.[0]&&typeof uploadFotoManutencao==='function')url=await uploadFotoManutencao(files[i].files[0],`INST-${Date.now()}`,etapas[i]);
      if(url)fotos[etapas[i]]=url;
    }
    const payload={agendamento_id:agendamentoId,cliente_id:cl?.id||null,unidade_id:un?.id||null,cliente:cl?.nome||null,unidade:un?.nome||null,municipio:o.municipio||null,data:o.data||null,responsavel_tecnico:o.responsavel_tecnico||null,produto:o.produto||null,volume:o.volume||null,componentes:componentesInstalacao(fd),local_instalacao:o.local_instalacao||null,origem_efluente:o.origem_efluente||null,checklist:checks,observacoes:o.observacoes||null,foto_antes:fotos.antes||null,foto_durante:fotos.durante||null,foto_depois:fotos.depois||null};
    const r=await fetch(`${SUPABASE_URL}/rest/v1/instalacoes`,{method:'POST',headers:{...SUPABASE_HEADERS,Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());
    if(agendamentoId&&typeof marcarAgendamentoConcluido==='function'){try{await marcarAgendamentoConcluido(agendamentoId);}catch(errAgenda){console.error(errAgenda);alert('O POP foi salvo, mas o agendamento não pôde ser marcado como concluído.');}}
    if(window.NAP_PHOTO_AUTOSAVE?.clearForm)try{await window.NAP_PHOTO_AUTOSAVE.clearForm(form);}catch(_){ }
    alert(agendamentoId?'Instalação executada, POP salvo e agendamento concluído.':'POP de instalação salvo na nuvem.');form.reset();form.querySelector('input[name="agendamento_id"]')?.remove();document.getElementById('instAgendamentoAviso')?.remove();produtoInstalacaoMudou();if(typeof carregarAgendaInstalacoes==='function')await carregarAgendaInstalacoes();if(typeof renderPainelManutencoes==='function')renderPainelManutencoes();showPage('home');
  }catch(err){console.error(err);alert('Não foi possível salvar o POP de instalação. As fotos capturadas permanecem protegidas no aparelho e serão sincronizadas quando houver internet.');}finally{if(btn){btn.disabled=false;btn.textContent='Salvar instalação';}}
}
function mostrarRegistroInstalacao(){document.getElementById('instalacaoForm').style.display='block';document.getElementById('agendaInstalacaoBox').style.display='none';}
function mostrarAgendaInstalacao(){document.getElementById('instalacaoForm').style.display='none';document.getElementById('agendaInstalacaoBox').style.display='block';if(typeof carregarAgendaInstalacoes==='function')carregarAgendaInstalacoes();}
(function iniciarPOPInstalacao(){const form=document.getElementById('instalacaoForm');if(!form)return;document.getElementById('instClienteSelect')?.addEventListener('change',preencherUnidadesInstalacao);document.getElementById('instUnidadeSelect')?.addEventListener('change',aplicarUnidadeInstalacao);document.getElementById('instProduto')?.addEventListener('change',produtoInstalacaoMudou);form.addEventListener('submit',e=>{e.preventDefault();salvarInstalacao(form);});setTimeout(preencherClientesInstalacao,300);produtoInstalacaoMudou();const baseShow=showPage;showPage=function(id){baseShow(id);if(id==='instalacao'){if(!clientesCache.length)carregarClientesUnidades().then(preencherClientesInstalacao);else preencherClientesInstalacao();}};})();