(()=>{
  const BUCKET='manutencoes-fotos';
  let blobAtual=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function sessao(){try{return JSON.parse(localStorage.getItem('napricelo_auth_session')||'null')}catch(_){return null}}
  function headers(extra={}){const jwt=sessao()?.access_token;if(!jwt)throw new Error('Faça login novamente.');return {apikey:SUPABASE_KEY,Authorization:`Bearer ${jwt}`,...extra}}
  async function obter(id){const local=window.historicoInstalacoesCache?.find(x=>Number(x.id)===Number(id));if(local)return local;const r=await fetch(`${SUPABASE_URL}/rest/v1/instalacoes?select=*&id=eq.${Number(id)}&limit=1`,{headers:SUPABASE_HEADERS});if(!r.ok)throw new Error(await r.text());return (await r.json())[0]||null}
  async function atualizar(id,payload){const r=await fetch(`${SUPABASE_URL}/rest/v1/instalacoes?id=eq.${Number(id)}`,{method:'PATCH',headers:{...headers(), 'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());const x=(await r.json())[0];const a=window.historicoInstalacoesCache||[];const i=a.findIndex(v=>Number(v.id)===Number(id));if(i>=0)a[i]=x;return x}
  function pathDaTRT(url){const s=String(url||''),marca=`/storage/v1/object/public/${BUCKET}/`,i=s.indexOf(marca);return i>=0?decodeURIComponent(s.slice(i+marca.length)):''}
  async function blobUrl(url){const path=pathDaTRT(url);if(!path)throw new Error('Caminho da TRT não identificado.');const r=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/${BUCKET}/${encodeURI(path)}`,{headers:headers()});if(!r.ok)throw new Error(await r.text());const b=await r.blob();if(blobAtual)URL.revokeObjectURL(blobAtual);blobAtual=URL.createObjectURL(b);return blobAtual}
  async function enviar(file,inst){if(!file||file.type!=='application/pdf')throw new Error('Selecione um PDF da TRT.');if(file.size>15*1024*1024)throw new Error('O PDF deve ter no máximo 15 MB.');const safe=`INST-${String(inst.id).padStart(5,'0')}`;const path=`${safe}/trt/${Date.now()}-${crypto.randomUUID()}.pdf`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${path}`,{method:'POST',headers:headers({'Content-Type':'application/pdf','x-upsert':'false'}),body:file});if(!r.ok)throw new Error(await r.text());return `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${path}`}

  window.anexarTRTInstalacao=async function(id){try{const inst=await obter(id);if(!inst)return alert('Instalação não encontrada.');const inp=document.createElement('input');inp.type='file';inp.accept='application/pdf,.pdf';inp.style.display='none';document.body.appendChild(inp);inp.onchange=async()=>{try{const f=inp.files?.[0];if(!f)return;const url=await enviar(f,inst);await atualizar(id,{trt_pdf_url:url,trt_pdf_nome:f.name||'TRT.pdf',trt_pdf_anexado_em:new Date().toISOString()});alert('TRT anexada com sucesso à instalação.');atualizarBotoes(id);mostrarPreview(id,true)}catch(e){console.error(e);alert('Não foi possível anexar a TRT. '+(e.message||''))}finally{inp.remove()}};inp.click()}catch(e){console.error(e);alert('Não foi possível preparar o anexo da TRT. '+(e.message||''))}}
  window.visualizarTRTInstalacao=async function(id){try{const inst=await obter(id);if(!inst?.trt_pdf_url)return alert('Nenhuma TRT anexada a esta instalação.');const u=await blobUrl(inst.trt_pdf_url);window.open(u,'_blank')}catch(e){console.error(e);alert('Não foi possível abrir a TRT. '+(e.message||''))}}

  function acoesHtml(x){const tem=!!x?.trt_pdf_url,id=Number(x?.id)||0;return `<div class="inst-trt-acoes" data-inst-trt="${id}" style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><button class="action" type="button" onclick="anexarTRTInstalacao(${id})">${tem?'Substituir TRT / PDF':'Anexar TRT / PDF'}</button><button class="action" type="button" onclick="visualizarTRTInstalacao(${id})" ${tem?'':'style="display:none"'}>Visualizar TRT</button></div>${tem?`<div class="detail-note inst-trt-status"><b>TRT anexada:</b> ${esc(x.trt_pdf_nome||'Documento TRT')}</div>`:''}`}
  const conteudoBase=window.conteudoInstalacao;
  if(typeof conteudoBase==='function'&&!conteudoBase.__trtInst){const wrap=function(x,comBotao=true){let h=conteudoBase.apply(this,arguments);if(comBotao&&x?.id&&!h.includes('inst-trt-acoes'))h+=acoesHtml(x);return h};wrap.__trtInst=true;window.conteudoInstalacao=wrap}

  async function atualizarBotoes(id){const inst=await obter(id);document.querySelectorAll(`[data-inst-trt="${Number(id)}"]`).forEach(box=>{const bs=box.querySelectorAll('button');if(bs[0])bs[0].textContent=inst?.trt_pdf_url?'Substituir TRT / PDF':'Anexar TRT / PDF';if(bs[1])bs[1].style.display=inst?.trt_pdf_url?'':'none';});}
  async function mostrarPreview(id,forcar=false){try{const inst=await obter(id);if(!inst?.trt_pdf_url)return;let box=document.querySelector(`[data-inst-trt-preview="${Number(id)}"]`);if(!box){const a=document.querySelector(`[data-inst-trt="${Number(id)}"]`);if(!a)return;box=document.createElement('div');box.dataset.instTrtPreview=String(id);box.className='trt-preview';a.insertAdjacentElement('afterend',box)}else if(!forcar&&box.querySelector('iframe'))return;const u=await blobUrl(inst.trt_pdf_url);box.innerHTML=`<div class="trt-preview-head"><b>TRT anexada</b><span>${esc(inst.trt_pdf_nome||'Documento TRT')}</span></div><iframe title="TRT anexada" src="${u}#toolbar=1&navpanes=0&view=FitH" style="width:100%;height:520px;border:1px solid #d8e2dd;border-radius:8px"></iframe>`}catch(e){console.warn(e)}}

  const relBase=window.gerarRelatorioInstalacao;
  if(typeof relBase==='function'&&!relBase.__trtInst){const wrap=function(id){const abrir=window.open;let janela=null;window.open=function(){janela=abrir.apply(window,arguments);return janela};try{return relBase.apply(this,arguments)}finally{window.open=abrir;if(janela)setTimeout(async()=>{try{const inst=await obter(id);if(!inst?.trt_pdf_url)return;const d=janela.document;if(d.querySelector('.inst-trt-rel'))return;const legal=d.querySelector('.legal');if(!legal)return;const box=d.createElement('div');box.className='inst-trt-rel';box.style.cssText='margin-top:12px;border:1px solid #b9d3c5;background:#f4f8f6;padding:10px 12px;font-size:11px;line-height:1.4';box.innerHTML=`<b>Responsabilidade técnica / TRT</b><br>Documento da TRT: PDF anexado ao registro eletrônico desta instalação.<br><span style="color:#61736a">${esc(inst.trt_pdf_nome||'TRT.pdf')}</span>`;legal.insertAdjacentElement('beforebegin',box)}catch(e){console.warn('TRT não inserida no relatório de instalação',e)}},150)}};wrap.__trtInst=true;window.gerarRelatorioInstalacao=wrap}

  function varrer(){document.querySelectorAll('.record button[onclick^="verInstalacaoHistorico"]').forEach(btn=>{const rec=btn.closest('.record');if(!rec||rec.querySelector('.inst-trt-lista'))return;const idx=Number((btn.getAttribute('onclick')||'').match(/\((\d+)\)/)?.[1]);const x=window.historicoInstalacoesCache?.[idx];if(!x?.id)return;const box=document.createElement('div');box.className='inst-trt-lista mini-actions';box.style.marginTop='6px';box.innerHTML=`<button class="action" type="button" onclick="anexarTRTInstalacao(${Number(x.id)})">${x.trt_pdf_url?'Substituir TRT':'Anexar TRT'}</button>${x.trt_pdf_url?`<button class="action" type="button" onclick="visualizarTRTInstalacao(${Number(x.id)})">Visualizar TRT</button>`:''}`;rec.appendChild(box)})}
  new MutationObserver(varrer).observe(document.body,{childList:true,subtree:true});setInterval(varrer,1600);setTimeout(varrer,500);
})();