(()=>{
const AUTH_KEY='napricelo_auth_session';
const state={perfil:null,ativo:false,permissoes:{}};
const DEFAULTS={
 administrador:['*'],
 tecnico:['painel','clientes','equipamentos','instalacoes','pop','analises','historico','exportar','agenda','relatorios','trt'],
 operacional:['painel','instalacoes','pop','analises','historico','agenda','relatorios'],
 comercial:['clientes','vendas','agenda','historico','exportar'],
 consulta:['painel','clientes','historico','exportar','agenda']
};
const writeBlocked=new Set(['consulta']);
function session(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
async function loadRole(){const s=session();if(!s?.access_token||!s.user?.id)return null;const r=await fetch(`${SUPABASE_URL}/rest/v1/app_user_roles?select=perfil,ativo,nome,email,permissoes&user_id=eq.${encodeURIComponent(s.user.id)}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${s.access_token}`}});if(!r.ok)return null;const a=await r.json();return a?.[0]||null}
function capsAtivas(){if(state.perfil==='administrador')return new Set(['*']);const p=state.permissoes||{};if(p.mode==='custom'&&Array.isArray(p.allowed))return new Set(p.allowed);const s=new Set(DEFAULTS[state.perfil]||[]);(Array.isArray(p.extras)?p.extras:[]).forEach(x=>s.add(x));(Array.isArray(p.disabled)?p.disabled:[]).forEach(x=>s.delete(x));return s}
function pode(cap){const s=capsAtivas();return s.has('*')||s.has(cap)}
window.NAPRICELO_PODE=pode;window.NAPRICELO_DEFAULT_PERMISSIONS=DEFAULTS;
function cardCap(c){if(c.id==='adminUsersCard')return 'admin';if(c.id==='cardComercial')return 'vendas';const t=(c.innerText||c.textContent||'').replace(/\s+/g,' ').trim();if(/Manutenções \/ Alertas|Alertas/.test(t))return 'painel';if(/Clientes \/ Unidades|^CL\s|Clientes/.test(t))return 'clientes';if(/Cadastrar equipamento|Novo equipamento|Equipamento/.test(t))return 'equipamentos';if(/POP \/ Agenda Instalação/.test(t))return 'instalacoes';if(/POP Biodigestor|POP Caixa|Água e Óleo|Caixa de Areia/.test(t))return 'pop';if(/Coleta \/ Análise/.test(t))return 'analises';if(/Histórico/.test(t))return 'historico';if(/Exportar registros/.test(t))return 'exportar';if(/Agenda Geral/.test(t))return 'agenda';return null}
function applyCards(){if(!state.perfil)return;document.querySelectorAll('#home .card,.dash-shortcut,.quick-card,.atalho-card').forEach(c=>{const cap=cardCap(c);if(!cap)return;c.style.display=pode(cap)?'':'none'});const adm=document.getElementById('adminUsersCard');if(adm)adm.style.display=state.perfil==='administrador'?'flex':'none';}
function applySpecialActions(){document.querySelectorAll('[data-relatorio-tecnico-os]').forEach(b=>b.style.display=pode('relatorios')?'':'none');document.querySelectorAll('[data-trt-os],[data-trt-abrir-os]').forEach(b=>b.style.display=pode('trt')?'':'none');document.querySelectorAll('button').forEach(b=>{const t=(b.innerText||b.textContent||'').trim();if(/^Agendar\b|Agenda comercial|Agendar manutenção/i.test(t)){if(!pode('agenda'))b.style.display='none'}if(/Relatório técnico|Imprimir OS \/ PDF/i.test(t)){if(!pode('relatorios'))b.style.display='none'}if(/TRT|ART/i.test(t)){if(!pode('trt'))b.style.display='none'}});const com=document.getElementById('comercial');if(com&&!pode('vendas')&&com.classList.contains('active'))showPage('home');}
function applyReadOnly(){document.getElementById('permBanner')?.remove();if(!writeBlocked.has(state.perfil))return;const banner=document.createElement('div');banner.id='permBanner';banner.textContent='Perfil Consulta: acesso somente para visualização. Cadastros e alterações estão bloqueados.';banner.style.cssText='max-width:960px;margin:12px auto;padding:10px 12px;border-radius:9px;background:#fff6d8;color:#6f5712;border:1px solid #eadb9b;font-size:13px';document.querySelector('main')?.prepend(banner);document.querySelectorAll('form button[type="submit"], form button:not([type]), button.primary').forEach(b=>{b.disabled=true;b.title='Perfil somente consulta'});document.querySelectorAll('form input, form textarea, form select').forEach(el=>{el.disabled=true});}
function label(){let el=document.getElementById('profileBadge');if(!el){el=document.createElement('span');el.id='profileBadge';el.style.cssText='margin-left:8px;padding:3px 7px;border-radius:10px;background:#e7f3ed;color:#176b45;font-size:11px;font-weight:700';document.querySelector('#authUser')?.appendChild(el)}if(el)el.textContent=state.perfil?state.perfil.toUpperCase():''}
async function init(){const r=await loadRole();if(!r?.ativo){state.perfil=null;state.ativo=false;return}state.perfil=r.perfil;state.permissoes=r.permissoes||{};state.ativo=true;window.NAPRICELO_PERFIL=r.perfil;window.NAPRICELO_PERMISSOES=state.permissoes;applyCards();applySpecialActions();applyReadOnly();label();setTimeout(()=>{applyCards();applySpecialActions()},800);setTimeout(()=>{applyCards();applySpecialActions()},1800)}
const mo=new MutationObserver(()=>{if(state.perfil){applyCards();applySpecialActions()}});mo.observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('load',()=>setTimeout(init,500));window.addEventListener('napricelo-auth-changed',()=>setTimeout(init,250));
function loadExtra(src){return new Promise((resolve,reject)=>{if(document.querySelector(`script[src*="${src}"]`))return resolve();const s=document.createElement('script');s.src=`${src}?v=67`;s.onload=resolve;s.onerror=reject;document.body.appendChild(s);});}
window.addEventListener('load',()=>setTimeout(()=>{Promise.resolve().then(()=>loadExtra('comercial-edicao.js')).then(()=>loadExtra('correcao-v63.js')).then(()=>loadExtra('share-proposta-main.js')).then(()=>loadExtra('comercial-responsaveis.js')).catch(e=>console.warn('Falha ao carregar recursos comerciais adicionais',e));},900));
})();